### ISSUE TITLE
[Bug Report] UNHANDLED_REJECTION: Error: Unable to reply context, because: Unknown interaction

### ISSUE THREAD

**Issue by MoustacheOff** [stegripe/rawon#1070]
### Describe the bug

```
Error: Unable to reply context, because: Unknown interaction
    at CommandContext.reply (file:///rawon/dist/structures/CommandContext.js:18:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///misc/vibin/dist/commands/music/LyricsCommand.js:43:25
```

### To Reproduce

1. Start the bot
2. Execute the lyrics command
3. See error(s)

### Expected behavior

Display the requested lyrics

### Operating System

Ubuntu 22.04.1

### Additional context

Node.js version: 18.12.1               
Discord.js version: 13.12.0               
FFmpeg version: 5.0.1

**Comment by MoustacheOff** [comment]
Also, Spotify links (tracks & playlists) doesn't work for me anymore.

**Comment by MoustacheOff** [comment]
Same for the warn command:
`UNHANDLED_REJECTION: Error: Unable to reply context, because: Unknown interaction`

**Comment by MoustacheOff** [comment]
Seems to have been fixed with the latest commits.
