### ISSUE TITLE
[Question] Installation error

### ISSUE THREAD

**Issue by SyntaxCodez** [stegripe/rawon#336]
- C:\Users\chauv\Desktop\disc-11-1.60.5\start.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at start (C:\Users\chauv\Desktop\disc-11-1.60.5\start.js:30:5)
    at Object.<anonymous> (C:\Users\chauv\Desktop\disc-11-1.60.5\start.js:21:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\chauv\\Desktop\\disc-11-1.60.5\\start.js' ]

**Comment by fab1ofx** [comment]
Try install and compile, with:
```bash
$ npm i && npm run compile
```

If using a operation **Windows** recommended to install **Build Tools**, with:
```bash
$ npm i windows-build-tools --global
```
Using a **PowerShell as Administrator**, or

Download a **[Python 2.7.15](https://www.python.org/ftp/python/2.7.15/python-2.7.15.amd64.msi)**, **[Build Tools 2017](https://download.visualstudio.microsoft.com/download/pr/3e542575-929e-4297-b6c6-bef34d0ee648/639c868e1219c651793aff537a1d3b77/vs_buildtools.exe)** and install as manuals.

Then, try install dependency and compile again.

**Comment by mzrtamp** [comment]
For further help, please go to our Discord server at [discord.gg/zhycorp](https://discord.gg/zhycorp) instead of opening an issues

**Comment by SyntaxCodez** [comment]
I had tried that but still getting the same errors

**Comment by mzrtamp** [comment]
Baca README asu
